### ISSUE TITLE
Mapbox layers - separating wards, divisions, and the base layer

### ISSUE THREAD

**Issue by akreider** [reclaimphiladelphia/reclaim_map#12]
I think the wards, divisions, and the base layer are all combined into a single layer.  Currently map.on() adds the entire thing and map.addLayer isn't necessary for displaying the outlined layers.

I propose five layers
1) base  - OSM (open street maps)
2) ward_hover - all the wards outlined
3) wards_click - highlights the ward that you clicked on
4) divisions layer - all the divisions outlined
5) divisions_click - highlights the division you clicked on

Can this proposal work with MapBox?  If so, what needs to be done?

We will want to show the base layer always. Next we have the choice of displaying 
1) wards  (hover and click)
2) divisions (hover and click) 
or 3) wards and divisions  (hover for both, and I'd suggest division click)

**Comment by aerispaha** [comment]
I think `map.on()` adds everything because the wards and divisions layers are actually part of the Mapbox "style" that I created in Mapbox studio. Those layers were added manually in Mapbox studio; I think you're right that they don't need to be added _again_ in the map_creation.js script. 

I don't think it's right to say they're all part of the same "Layer", but you're correct that they are combined into the same "Style". 

Mapbox provides a web-based user interface to style up maps, add layers, change colors, and labels, etc. Styles created there can then be easily dropped into an app, such as our map project, with a simple `map.on()` that references the style ID. Here's a snapshot of the Mapbox Studio interface showing many of the layers included in this "Style":
![image](https://user-images.githubusercontent.com/6521360/41550537-12091c24-72f7-11e8-9516-283d82504f41.png)

So, our map will have many more than 5 layers, but most of the layers will be built into the "basemap". Other than that, I agree that we will always show the base layers, in addition to the layers necessary for showing wards and divisions, in click and hover "mode".

**Comment by akreider** [comment]
I changed the style to initialize with the wards and divisions hidden.  If we use this method, I don't think we need data sources for them and the addlayer functions are very different from my previous design.

This does create an issue.  If we're embedding our layer logic in the MapBox style then we need to modify the style if we add additional layers.

In the near future we might want a function that reads a list of our layers, and then creates the MapBox style.  What do you think?  

For now I might stick to the easier method of manually editing the style.

**Comment by aerispaha** [comment]
I think that makes sense. Mapbox provides an [uploads api](https://www.mapbox.com/api-documentation/#uploads) that we can probably make use of in the future for a more streamlined process. But for now, manually editing is fine.
