### ISSUE TITLE
Find data sources: Race, Economics, Election Results

### ISSUE THREAD

**Issue by aerispaha** [reclaimphiladelphia/reclaim_map#7]
Find spatial data (geojson) for the following in Philadelphia:

- Race (e.g. block-level proportion of each race) 
- Economics (e.g. household income, unemployment)
- Election Results (huge topic, discussion probably needed on where to focus)

**Comment by akreider** [comment]
Did we have a Google Docs on this?

Race - 2010 census - I've got this.  If you want to see changes since 2010, it might be possible to do so using the American Community Survey (ACS) at the census tract level - though the confidence interval might be too large in most cases (and using income from the ACS might be a decent proxy).

Income - by census tract - ACS 5 year summary - I've got this.  (Other economics and many other ACS things  you could get from CensusReporter.org)

**Comment by aerispaha** [comment]
@akreider, I'm going to close this out. You've got Race and Income data, and @natlownes definitely has election results data. Let's make use of this data in more specific issues.
